apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-story
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Once mean one node can be claimed, but accept mulitple pods.
  hostPath:
    path: /data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: standard
  volumeName: pv-story
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi