apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: task-container
          image: rmc3408/kub-sec14-tasks:0.3
          env:
            - name: AUTH_SERVICE
              value: "auth-service.default" # Domain is SERVICE_NAME.NAMESPACE
            - name: TASKS_FOLDER
              value: tasks
