apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: user-container
          image: rmc3408/kub-sec14-users:0.2
          env:
            - name: AUTH_ADDRESS
              # value: localhost #if inside same POD
              # value: "10.108.107.236" # Manual IP address from kubectl get services
              value: "auth-service.default" # Domain is SERVICE_NAME.NAMESPACE
        # - name: auth-container
        #   image: rmc3408/kub-sec14-auth:0.1
