apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
      - name: node-simple
        image: rmc3408/node-simple-img:0.2
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: node-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer