apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: node-pod
  template:
    metadata:
      labels:
        pod: node-pod
        app: node-app
    spec:
      containers:
      - name: node-sec12-app
        image: rmc3408/node-remote-sec12
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    pod: node-pod
spec:
  selector:
    pod: node-pod
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: NodePort
