version: "3.8"

services:
  server: # web server for laravel php
    # image: nginx:stable-alpine
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    ports: 
      - 8000:80
    # volumes:  ## THIS WON'T BE HAPPENING IN PRODUCTION, changes made in dockerfile COPY command.
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php: # php engine
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    # volumes:
    #   - ./src:/var/www/html:delegated # refresh in batch, improve performance, no refresh immediately
  mysql:
    image: mysql:5.7.43
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=homestay

  composer: # package manage in php
    build:
      context: ./docker
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan: # manage database migration and update
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - mysql

  npm: # add node npm for resources/view javascript packages
    image: node:alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html